app/shop/models.py
from flask_login import UserMixin
from app import db, login

from enum import unique
from hashlib import md5
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
from sqlalchemy.ext.hybrid import hybrid_property
from slugify import slugify

from app.catalog.models import Product, ProductStock

class ShoppingCartItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # -----------Relational fields-----------
    cart_id = db.Column(db.Integer, db.ForeignKey('shopping_cart.id'))
    product_stock_id = db.Column(db.Integer, db.ForeignKey('product_stock.id'))
    quantity = db.Column(db.Integer, default=1)
    price = db.Column(db.Numeric(scale=2), nullable=False)

    @property
    def product(self):
        product_stock = ProductStock.query.get(self.product_stock_id)
        product = Product.query.get(product_stock.product_id)
        return product
    
    @property
    def total_price(self):
        return self.quantity * self.price

class ShoppingCart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # -----------Relational fields-----------
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    items = db.relationship('ShoppingCartItem', backref='cart', lazy=True)

    @property
    def total_price(self):
        return sum(item.total_price for item in self.items)

    @property
    def __len__(self):
        return len(self.items)

    def clear(self):
        for item in self.items:
            item.delete()

    

app/shop/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, IntegerField
from wtforms.fields.html5  import EmailField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Length

from app.auth.models import User


class AddToCartForm(FlaskForm):
    quantity = IntegerField('Quantidade', default=1)
    submit = SubmitField('Adicionar à sacola')

app/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__)

from app.shop import routes

app/shop/routes.py
from flask import render_template, request, redirect, url_for, session
from flask_login import current_user, login_required

from werkzeug.urls import url_parse
from datetime import datetime, timedelta

#from app import dummy_data

from app.shop.cart import CartManager
from app.catalog.models import Product, Category, ProductStock
from app.shop import bp
from app.shop.forms import AddToCartForm

@bp.route('/')
@bp.route('/index')
@bp.route('/categoria/<category_slug>')
def index(category_slug=None):
    categories = Category.query.all()
    if category_slug:
        category = Category.query.filter_by(slug = category_slug).first()
        products = Product.query.filter_by(category_id = category.id).all()
    else:
        products = Product.query.all()

    cart = CartManager(session, current_user).get_cart()
    
    return render_template('shop/index.html', title="Produtos", products=products, categories=categories,cart = cart)

@bp.route('/minha_conta')
@login_required
def user_account():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    cart = CartManager(session, current_user).get_cart()
    return render_template('shop/profile.html', title="Minha Conta", current_user=current_user, cart=cart)
    

@bp.route('/produto/<product_slug>', methods=['GET', 'POST'])
def product_detail(product_slug):
    product = Product.query.filter_by(slug = product_slug).first()
    cart = CartManager(session, current_user).get_cart()
    addToCartForm = AddToCartForm()
    if addToCartForm.validate_on_submit():
        product_stock = ProductStock.query.filter_by(product_id = product.id).first()
        cart_manager = CartManager(session, current_user)
        print('SESSION CART ID = ',session['CART_ID'])
        cart_manager.add(product_stock, addToCartForm.quantity.data)
        return redirect(url_for('shop.shopping_cart'))
    return render_template('shop/product_detail.html', title=product.name, product = product, current_user=current_user, cart=cart, addToCartForm = addToCartForm)

@bp.route('/sacola')
def shopping_cart():
    cart_manager = CartManager(session, current_user)
    print('CART = ', session['CART_ID'])
    cart = cart_manager.get_cart()
    return render_template('shop/shopping_cart.html', title='Minha Sacola', current_user=current_user, cart=cart)

app/templates/shop/index.html
{% extends "_base.html"%}
{% set body_class = 'layout-top-nav' %}

{% block title %}
Produtos | Painel | Bootshop
{% endblock %}

{% block content %}

  {% include 'shop/navbar.html' %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"> Top Navigation <small>Example 3.0</small></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Top Navigation</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                        {% for category in categories %}
                        
                            <a href="{{ url_for('shop.index', category_slug=category.slug)}}" class="card-link">{{ category.name }}</a>
                            <br>
                        {% endfor %}
                    </div>
                  </div>    
            </div>
            
          <div class="col-lg-9">
            <div class="row">
            {% for product in products %}
            
            <div class="col-lg-3">
            <div class="card">
              <div class="card-body">
                <a href="{{ url_for('shop.product_detail', product_slug=product.slug) }}"><img src="{{ product.thumbnail }}" alt=""></a>
                <br>
                <h5 class="card-text">{{ product.name }}</h5>
                <p class="card-text">{% if product.total_stock %}R$ {{ product.price }}{% else %} Preço não disponível {% endif %}</p>
                <p class="card-text">{% if product.total_stock %}Em estoque {% else %} Esgotado {% endif %}</p>

                <a href="#" class="card-link">Adicionar à cesta</a>
              </div>
            </div>
          </div>
            
            
          <!-- /.col-md-6 -->
          {% endfor  %}
        </div>
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  {% endblock %}

app/templates/shop/navbar.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="{{ url_for('shop.index') }}" class="navbar-brand">
        <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Bootshop</span>
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            
            <a href="{{ url_for('shop.user_account') }}" class="nav-link">{% if current_user.is_authenticated %}Conta{% else %}Entrar{% endif %}</a>
            
          </li>
          <li class="nav-item dropdown">
            <a id="dropdownSubMenuShop" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Navegar na loja</a>
            <ul aria-labelledby="dropdownSubMenuShop" class="dropdown-menu border-0 shadow">
              <li><a href="{{ url_for('shop.index') }}" class="dropdown-item">Todos os produtos</a></li>
              <li class="dropdown-divider"></li>
              <!-- Level two dropdown Categories-->
              <li class="dropdown-submenu dropdown-hover">
                <a id="dropdownSubMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle">Categorias</a>
                <ul aria-labelledby="dropdownSubMenu2" class="dropdown-menu border-0 shadow">
                  
                    {% for category in categories %}
                    <li>
                      <a tabindex="-1" href="{{ url_for('shop.index', category_slug=category.slug)}}" class="dropdown-item">{{ category.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
              </li>
              <!-- End Level two Categories-->
              <!-- Level two dropdown Offers -->
              <li class="dropdown-submenu dropdown-hover">
                <a id="dropdownSubMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-item dropdown-toggle">Ofertas</a>
                <ul aria-labelledby="dropdownSubMenu2" class="dropdown-menu border-0 shadow">
                    {% if offers %}
                      {% for offer in offers %}
                      <li>
                        <a tabindex="-1" href="{{ url_for('shop.index', offer_slug=offer.slug)}}" class="dropdown-item">{{ offer.name }}</a>
                      </li>
                      {% endfor %}
                    {% else %}
                    <li>
                      <a tabindex="-1" href="#" class="dropdown-item">Não há ofertas no momento</a>
                    </li>
                    {% endif %}
                </ul>
              </li>
              <!-- End Level two Offers -->
            </ul>
          </li>
          {% if current_user.is_staff %}
          <li class="nav-item">
            <a href="{{ url_for('dashboard.index') }}" class="nav-link">Painel</a>
          </li>
          {% endif %}
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-0 ml-md-3">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Pesquisar na loja" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
      </div>

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        {% include "navbar_messages.html" %}
        {% include "navbar_notifications.html" %}

        <!-- Shopping cart dropdown menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="{{ url_for('shop.shopping_cart')}}">
            <i class="fas fa-shopping-bag"></i>
            <span class="badge badge-warning navbar-badge">{{ cart.items|length }}</span>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <span class="dropdown-header">{{ cart.items|length }} produtos na sacola</span>
            {% for item in cart.items %}
            <div class="dropdown-divider"></div>
            <a href="{{ url_for('shop.product_detail', product_slug=item.product.slug) }}" class="dropdown-item">
              <img src="{{ item.product.thumbnail }}" alt="imagem do produto">{{ item.product.name }} ({{ item.quantity }})
              <span class="float-right text-muted text-sm">R$ {{ item.price }}</span>
            </a>
            {% endfor %}
            <div class="dropdown-divider"></div>
            <div class="dropdown-divider"></div>
            <p class="dropdown-item dropdown-footer">Total: R$ {{ cart.total_price }} (+ frete)</p>
            <a href="{{ url_for('shop.shopping_cart') }}" class="dropdown-item dropdown-footer">Ver sacola</a>
          </div>
        </li>
        <!-- End Shopping cart -->

        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('auth.logout') }}" class="nav-link {% if not current_user.is_authenticated %} disabled {% endif %} ">Sair</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->

app/templates/shop/product_detail.html
{% extends "_base.html"%}
{% set body_class = 'layout-top-nav' %}

{% block title %}
Produtos | Painel | Bootshop
{% endblock %}

{% block content %}

  {% include 'shop/navbar.html' %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>E-commerce</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">E-commerce</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-solid">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-sm-6">
              <h3 class="d-inline-block d-sm-none">{{ product.name }}</h3>
              <div class="col-12">
                <img src="{{ product.thumbnail }}" class="product-image" alt="Product Image">
              </div>
              <div class="col-12 product-image-thumbs">
                <div class="product-image-thumb active"><img src="../../dist/img/prod-1.jpg" alt="Product Image"></div>
                <div class="product-image-thumb" ><img src="../../dist/img/prod-2.jpg" alt="Product Image"></div>
                <div class="product-image-thumb" ><img src="../../dist/img/prod-3.jpg" alt="Product Image"></div>
                <div class="product-image-thumb" ><img src="../../dist/img/prod-4.jpg" alt="Product Image"></div>
                <div class="product-image-thumb" ><img src="../../dist/img/prod-5.jpg" alt="Product Image"></div>
              </div>
            </div>
            <div class="col-12 col-sm-6">
              <h3 class="my-3">{{ product.name }}</h3>
              <p>{% if product.description|length > 100 %}{{ product.description[:100] }}{% else %}{{ product.description }}{% endif %}</p>

              <hr>
              <h4>Available Colors</h4>
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-default text-center active">
                  <input type="radio" name="color_option" id="color_option_a1" autocomplete="off" checked>
                  Green
                  <br>
                  <i class="fas fa-circle fa-2x text-green"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a2" autocomplete="off">
                  Blue
                  <br>
                  <i class="fas fa-circle fa-2x text-blue"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a3" autocomplete="off">
                  Purple
                  <br>
                  <i class="fas fa-circle fa-2x text-purple"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a4" autocomplete="off">
                  Red
                  <br>
                  <i class="fas fa-circle fa-2x text-red"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a5" autocomplete="off">
                  Orange
                  <br>
                  <i class="fas fa-circle fa-2x text-orange"></i>
                </label>
              </div>

              <h4 class="mt-3">Size <small>Please select one</small></h4>
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b1" autocomplete="off">
                  <span class="text-xl">S</span>
                  <br>
                  Small
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b2" autocomplete="off">
                  <span class="text-xl">M</span>
                  <br>
                  Medium
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b3" autocomplete="off">
                  <span class="text-xl">L</span>
                  <br>
                  Large
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b4" autocomplete="off">
                  <span class="text-xl">XL</span>
                  <br>
                  Xtra-Large
                </label>
              </div>

              {% if product.total_stock %}
              <div class="py-2 px-3 mt-4">
                <h2 class="mb-0">
                  R$ {{ product.price }}
                </h2>
              </div>
            
              <!-- Freight form -->
              <div class="card card-info">
                <div class="card-header">
                  <h3 class="card-title">Calcular Frete</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal">
                  <div class="card-body">
                    <div class="form-group row">
                      <label for="inputEmail3" class="col-sm-2 col-form-label">CEP</label>
                      <div class="col-sm-10">
                        <input type="email" class="form-control" id="inputEmail3" placeholder="CEP">
                      </div>
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-info">Calcular</button>
                  </div>
                  <!-- /.card-footer -->
                </form>
                <div class="m-2">
                    <p>Insira um CEP acima para calcular</p>
                </div>
              </div>
              <!-- END Freight form -->
            
              
              <!-- Add to shopping cart -->
              <form action="" method="post" novalidate>
                {{ addToCartForm.hidden_tag() }}
                <div class="input-group input-group mb-3">
                    {{ addToCartForm.quantity.label(class="btn btn-info btn-flat") }}
                    {{ addToCartForm.quantity(class="form-control") }}
                    
                    {{ addToCartForm.submit(class="btn btn-info btn-flat") }}
                    
                </div>

              </form>
              <!-- END Add to shopping cart -->
              {% else %}
              <p>Produto Esgotado</p>
              {% endif %}
              

                <div class="btn btn-default btn-lg btn-flat">
                  <i class="fas fa-heart fa-lg mr-2"></i>
                  Adicionar à lista de desejos
                </div>
              </div>

              <div class="mt-4 product-share">
                <a href="#" class="text-gray">
                  <i class="fab fa-facebook-square fa-2x"></i>
                </a>
                <a href="#" class="text-gray">
                  <i class="fab fa-twitter-square fa-2x"></i>
                </a>
                <a href="#" class="text-gray">
                  <i class="fas fa-envelope-square fa-2x"></i>
                </a>
                <a href="#" class="text-gray">
                  <i class="fas fa-rss-square fa-2x"></i>
                </a>
              </div>

            </div>
          </div>
          <div class="row mt-4">
            <nav class="w-100">
              <div class="nav nav-tabs" id="product-tab" role="tablist">
                <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Descrição</a>
                <a class="nav-item nav-link" id="product-comments-tab" data-toggle="tab" href="#product-comments" role="tab" aria-controls="product-comments" aria-selected="false">Avaliações</a>
              </div>
            </nav>
            <div class="tab-content p-3" id="nav-tabContent">
              <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab">{{ product.description }}</div>
              
              <div class="tab-pane fade" id="product-comments" role="tabpanel" aria-labelledby="product-comments-tab">
                {% if product.product_reviews %}  
                    {% for review in product.product_reviews %}
                        {{ review.rating }}
                        {{ review.description }}
                    {% endfor %}
                {% else %}
                    Não há avaliações.
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </section>
      <!-- /.content -->
  </div>
  <!-- /.card -->

{% endblock %}

app/templates/shop/shopping_cart.html
{% extends "_base.html"%}
{% set body_class = 'layout-top-nav' %}

{% block title %}
Produtos | Painel | Bootshop
{% endblock %}

{% block content %}

  {% include 'shop/navbar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Produtos</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Painel</a></li>
              <li class="breadcrumb-item active">Produtos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
               

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Projects</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 20%">
                          Imagem
                      </th>
                      <th style="width: 10%">
                          Produto
                      </th>
                      <th style="width: 8%">
                          Quantidade
                      </th>
                      <th style="width: 8%" class="text-center">
                        Remover/ Modificar
                      </th>
                      <th style="width: 8%">
                        Preço unitário
                      </th>
                      <th style="width: 20%">
                        Preço
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {% for item in cart.items %}
                  <tr>
                      <td>
                        <a href="{{ url_for('shop.product_detail', product_slug=item.product.slug) }}">
                            <img alt="Product image" class="table-avatar" src="{{ item.product.thumbnail }}">
                        </a>
                        
                      </td>  
                      <td>
                          {{ item.product.name }}
                      </td>
                      
                      <td>
                        {{ item.quantity }}
                     </td>
                     <td class="text-center">
                        
                     </td> 
                     <td>
                        {{ item.price }}
                     </td>
                     <td>
                        {{ item.total_price }}
                     </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock %}