app/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from app.dashboard import routes

app/dashboard/routes.py
from flask import render_template, request, redirect, url_for, flash, send_from_directory
from flask_login import current_user, login_required

import os
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from datetime import datetime, timedelta

from app import db, app
from app.utils import allowed_image

from app.auth.models import User
from app.auth.permissions import staff_only
from app.catalog.forms import ProductForm
from app.catalog.models import Category, Product, ProductImage
from app.logistics.forms import AddressForm
from app.logistics.models import Address

from app.dashboard import bp


@bp.route('/')
@login_required
@staff_only
def index():

    #current_user = dummy_data.current_user
    
    #messages = dummy_data.Message

    #notifications = dummy_data.Notification
    
    today = datetime.today()
    first_day_curr_month = datetime(today.year, today.month, 1)
    if today.month > 1:
        first_day_prev_month = datetime(today.year, today.month-1, 1)
    else:
        first_day_prev_month = datetime(today.year-1, 12, 1)

    total_clients = User.query.filter_by(is_staff=False)
    current_month_clients = total_clients.filter(User.registered_at >= first_day_curr_month)
    prev_month_clients = total_clients.filter(User.registered_at < first_day_curr_month).filter(User.registered_at >= first_day_prev_month)
    if prev_month_clients.all():
        perc_month_inc_clients = ( len(current_month_clients.all()) - len(prev_month_clients.all()) )/len(prev_month_clients.all())*100
    else:
        perc_month_inc_clients = 100

    client_stats = { 'total': len(total_clients.all()) ,
                'new':  len(current_month_clients.all()),
                'perc_month': perc_month_inc_clients,
                'max': 'Not Implemented' }
    '''
    order_stats = {'total': dummy_data.get_orders_total(),
             'perc_month':dummy_data.get_orders_perc_month()}

    best_selling_products = dummy_data.get_best_selling_products()

    product_stats = {'total':len( dummy_data.Product.query.all() ),
                     'perc_month' : dummy_data.get_products_perc_month()}
    '''


    
    return render_template('dashboard/index.html', title='Painel', current_user=current_user,
                                                         #messages=messages,
                                                         #notifications=notifications,
                                                         client_stats = client_stats,
                                                         #order_stats = order_stats,
                                                         #best_selling_products = best_selling_products,
                                                         #product_stats = product_stats,
                                                         request = request
                                                         )



@bp.route('/produtos')
@login_required
@staff_only
def product_list():
    products = Product.query.all()
    if 'message' in request.args:
        message = request.args['message']  # counterpart for url_for()
    
    return render_template('dashboard/product_list.html', title="Catálogo",  products = products,
                                                                current_user=current_user,
                                                                request = request,
                                                                message = message)

@bp.route("/produtos/editar/<product_slug>", methods=["GET", "POST"])
@staff_only
@login_required
def product_edit(product_slug):
    product = Product.query.filter_by(slug=product_slug)
    success = False

    if request.method == "POST":
        form = ProductForm(request.form, obj=product)
        if form.validate():
            form.populate_obj(product)
            db.session.add(product)
            db.session.commit()
            success = True
    else:
        form = ProductForm(obj=product)

    return render_template("dashboard/product_add.html", form=form, success=success)

@bp.route("/produtos/adicionar", methods=["GET", "POST"])
@staff_only
@login_required
def product_add():
    success = False

    if request.method == "POST":
        form = ProductForm(request.form)
        if form.validate():
            product = Product(name=form.name.data, description=form.description.data, category_id=form.category.data.id)
            message = ''

            uploaded_files = request.files.getlist("files[]")
            #uploaded_file = request.files("file")
            for uploaded_file in uploaded_files:
                print('FILENAME = ', uploaded_file.filename)
                if uploaded_file and allowed_image(uploaded_file.filename):
                    filename = secure_filename(uploaded_file.filename)
                    image_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
                    uploaded_file.save(image_path)
                    product_image = ProductImage(image_url = image_path, image_filename=image_path, product_id = product.id)
                    db.session.add(product_image)
                    message += f'Imagem {image_path} criado com sucesso.\n' 
                    
            db.session.add(product)
            db.session.commit()
            message += 'Produto criado com successo.'
            return redirect(url_for('dashboard.product_list', message = message))
    else:
        form = ProductForm()

    return render_template("dashboard/product_add.html", form=form, success=success)



@bp.route('/uploads/<filename>')
def upload(filename):
    return send_from_directory(app.config['UPLOAD_PATH'], filename)


@bp.route('/categorias')
@login_required
@staff_only
def categories():
    categories = Category.query.all()
    
    return render_template('dashboard/categories.html', title="Catálogo",  categories = categories,
                                                                current_user=current_user,
                                                                request=request)


@bp.route('/enderecos')
@login_required
@staff_only
def address_list():
    if not current_user.is_authenticated:
        return redirect(url_for('index'))
    addresses = Address.query.filter_by(user_id = current_user.id).all()
    return render_template('auth/address_list.html',title="Endereços", addresses=addresses)

@bp.route('/enderecos/<address_id>', methods=['GET', 'POST'])
@login_required
@staff_only
def address_detail(address_id):
    address = Address.query.get(address_id)
    if not current_user.is_authenticated or not address.user_id == current_user.id:
        return redirect(url_for('index'))
    form = AddressForm(obj=address)
    if form.validate_on_submit():
        form.populate_obj(address)
        db.session.commit()
        flash('As mudanças no endereço foram salvas')
        return redirect(url_for('address_list'))
    return render_template('address_add.html', title='Editar Endereço',form=form)

@bp.route('/enderecos/novo', methods=['GET', 'POST'])
@login_required
@staff_only
def address_add():
    if not current_user.is_authenticated:
        return redirect(url_for('index'))
    form = AddressForm()
    if form.validate_on_submit():
        address = Address()
        form.populate_obj(address)
        db.session.add(address)
        db.session.commit()
        flash('O novo endereço foi salvo')
        return redirect(url_for('address_list'))
    return render_template('address_add.html', title='Adicionar Endereço',form=form)

app/templates/dashboard/best_selling_table.html
<div class="card">
    <div class="card-header border-0">
      <h3 class="card-title">Produtos mais vendidos</h3>
      <div class="card-tools">
        <a href="#" class="btn btn-tool btn-sm">
          <i class="fas fa-download"></i>
        </a>
        <a href="#" class="btn btn-tool btn-sm">
          <i class="fas fa-bars"></i>
        </a>
      </div>
    </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-striped table-valign-middle">
        <thead>
        <tr>
          <th>Produto</th>
          <th>Preço</th>
          <th>Vendas</th>
          <th>Mais</th>
        </tr>
        </thead>
        <tbody>
          {% for product in best_selling_products %}
        <tr>
          <td>
            <img src="https://picsum.photos/id/237/150" alt="Product 1" class="img-circle img-size-32 mr-2">
            {{ product.name }}
          </td>
          <td>R$ {{ product.price }}</td>
          <td>
            <small class="text-success mr-1">
              <i class="fas fa-arrow-up"></i>
              {{ product.perc_month }}%
            </small>
            {{ product.qty_sold }} vendido
          </td>
          <td>
            <a href="#" class="text-muted">
              <i class="fas fa-search"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- /.card -->

app/templates/dashboard/categories.html
{% extends "_base.html"%}
{% set body_class = 'sidebar-mini' %}

{% block title %}
Categorias | Painel | Bootshop
{% endblock %}

{% block content %}

  {% include 'dashboard/navbar.html' %}
  {% include 'dashboard/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Categorias</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Painel</a></li>
              <li class="breadcrumb-item active">Categorias</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        
        <!-- New product box -->
        <div class="container-fluid">
            
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">Criar nova categoria</h3>
                </div>
                <!-- /.card-header -->
                <div class="m-2 pr-5">
                    <button type="button" class="btn btn-primary"><i class="fas fa-plus-circle"></i>Nova Categoria</button>
                </div>
            </div>
        </div>
        <!-- End New product box -->

        <!-- Search box -->
        <div class="container-fluid">
            
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">Procurar Categorias</h3>
                </div>
                <!-- /.card-header -->
                <div class="input-group input-group-sm m-2 pr-5">
                    <input type="text" class="form-control">
                    <span class="input-group-append">
                      <button type="button" class="btn btn-info btn-flat">Pesquisar</button>
                    </span>
                  </div>
            </div>
        </div>
        <!-- End Search box -->

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Categorias</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 10%">
                          Nome
                      </th>
                      <th style="width: 10%">
                          Descrição
                      </th>
                      <th style="width: 8%" class="text-center">
                          Número de sub categorias
                      </th>
                      <th style="width: 8%" class="text-center">
                        Público
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {% for category in categories %}
                  <tr>
                      <td>
                          {{ category.name }}
                      </td>
                      <td>
                        {{ category.description }}
                      </td>
                      <td  class="text-center">
                        <a href="link to list of subcategories">{{ category.sub_categories|length }}</a>
                     </td>
                     <td class="project-state">
                        {% if  category.is_available %}
                            <span class="badge badge-success">Sim</span>
                        {% else %}
                            <span class="badge badge-danger">Não</span>
                        {% endif %}
                    </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="#">
                              <i class="fas fa-folder">
                              </i>
                              Ver
                          </a>
                          <a class="btn btn-info btn-sm" href="#">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Editar
                          </a>
                          <a class="btn btn-danger btn-sm" href="#">
                              <i class="fas fa-trash">
                              </i>
                              Deletar
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

app/templates/dashboard/client_chart.html
<div class="card">
    <div class="card-header border-0">
      <div class="d-flex justify-content-between">
        <h3 class="card-title"># de Clientes</h3>
        <a href="javascript:void(0);">Ver relatório</a>
      </div>
    </div>
    <div class="card-body">
      <div class="d-flex">
        <p class="d-flex flex-column">
          <span class="text-bold text-lg">{{ client_stats.total }}</span>
          <span>visitantes todo o tempo</span>
        </p>
        <p class="ml-auto d-flex flex-column text-right">
          <span class="text-success">
            <i class="fas fa-arrow-up"></i> {{ client_stats.perc_month }}%
          </span>
          <span class="text-muted">comparado ao mês passado</span>
        </p>
      </div>
      <!-- /.d-flex -->

      <div class="position-relative mb-4">
        <canvas id="visitors-chart" height="200"></canvas>
      </div>

      <div class="d-flex flex-row justify-content-end">
        <span class="mr-2">
          <i class="fas fa-square text-primary"></i> Mês atual
        </span>

        <span>
          <i class="fas fa-square text-gray"></i> Mês passado
        </span>
      </div>
    </div>
  </div>
  <!-- /.card -->

app/templates/dashboard/order_chart.html
<div class="card">
    <div class="card-header border-0">
      <div class="d-flex justify-content-between">
        <h3 class="card-title">Vendas</h3>
        <a href="javascript:void(0);">Ver relatório</a>
      </div>
    </div>
    <div class="card-body">
      <div class="d-flex">
        <p class="d-flex flex-column">
          <span class="text-bold text-lg">{{ order_stats.total }}</span>
          <span>vendas já feitas</span>
        </p>
        <p class="ml-auto d-flex flex-column text-right">
          <span class="text-success">
            <i class="fas fa-arrow-up"></i> {{ order_stats.perc_month}}%
          </span>
          <span class="text-muted">comparado ao mês passado</span>
        </p>
      </div>
      <!-- /.d-flex -->

      <div class="position-relative mb-4">
        <canvas id="sales-chart" height="200"></canvas>
      </div>

      <div class="d-flex flex-row justify-content-end">
        <span class="mr-2">
          <i class="fas fa-square text-primary"></i> Ano atual ({{ year }})
        </span>

        <span>
          <i class="fas fa-square text-gray"></i> Ano passado
        </span>
      </div>
    </div>
  </div>
  <!-- /.card -->

app/templates/dashboard/product_list.html
{% extends "_base.html"%}
{% set body_class = 'sidebar-mini' %}

{% block title %}
Produtos | Painel | Bootshop
{% endblock %}

{% block content %}

  {% include 'dashboard/navbar.html' %}
  {% include 'dashboard/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Produtos</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Painel</a></li>
              <li class="breadcrumb-item active">Produtos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        
        <!-- New product box -->
        <div class="container-fluid">
            
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">Criar um novo produto</h3>
                </div>
                <!-- /.card-header -->
                <div class="m-2 pr-5">
                    <a href="{{ url_for('dashboard.product_add') }}" type="button" class="btn btn-primary"><i class="fas fa-plus-circle"></i>Novo Produto</a>
                    <!-- <button type="button" class="btn btn-primary"><i class="fas fa-plus-circle"></i>Novo Produto</button> -->
                    
                    {% if 'alerta' in message %}
                    <div class="alert alert-warning alert-dismissible">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                      <h5><i class="icon fas fa-check"></i>Atenção!</h5>
                      {{ message }}
                    </div>
                    {% else %}
                    <div class="alert alert-success alert-dismissible">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                      <h5><i class="icon fas fa-check"></i>Sucesso!</h5>
                      {{ message }}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- End New product box -->

        <!-- Search box -->
        <div class="container-fluid">
            
            <div class="card">
                <div class="card-header">
                <h3 class="card-title">Procurar Produtos</h3>
                </div>
                <!-- /.card-header -->
                <div class="input-group input-group-sm m-2 pr-5">
                    <input type="text" class="form-control">
                    <span class="input-group-append">
                      <button type="button" class="btn btn-info btn-flat">Pesquisar</button>
                    </span>
                  </div>
            </div>
        </div>
        <!-- End Search box -->

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Projects</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 20%">
                          Título (CUP)
                      </th>
                      <th style="width: 10%">
                          Imagem
                      </th>
                      <th style="width: 8%">
                          Categoria
                      </th>
                      <th style="width: 8%" class="text-center">
                        Qtde em estoque
                      </th>
                      <th style="width: 8%">
                        Data de atualização
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {% for product in products %}
                  <tr>
                      <td>
                          {{ product.name }}
                          <br/>
                          <small>
                              Not implemented
                          </small>
                      </td>
                      <td>
                        <img alt="Product image" class="table-avatar" src="{{ product.thumbnail }}">
                      </td>
                      <td>
                        <a href="link to category"></a>{{ product.category.name }}
                     </td>
                     <td class="text-center">
                        <span class="badge {% if  product.total_stock < 10 %}badge-danger{% else %}badge-success{% endif %}">{{ product.total_stock }}</span>
                     </td> 
                     <td>
                        {{ product.updated_at }}
                     </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="#">
                              <i class="fas fa-folder">
                              </i>
                              Ver
                          </a>
                          <a class="btn btn-info btn-sm" href="#">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Editar
                          </a>
                          <a class="btn btn-danger btn-sm" href="#">
                              <i class="fas fa-trash">
                              </i>
                              Deletar
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

app/templates/dashboard/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ url_for('static', filename = 'dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Bootshop</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ current_user.avatar }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ current_user.username }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      {% if current_user.is_staff %}
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ url_for('dashboard.index') }}" class="nav-link {% if 'dashboard' in request.endpoint %}active{% endif %}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Painel
              </p>
            </a>
          </li>
          <li class="nav-item menu-closed">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-sitemap"></i>
              <p>
                Catálogo
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ url_for('dashboard.product_list') }}" class="nav-link {% if 'products' in request.endpoint %}active{% endif %}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Produtos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('dashboard.categories') }}" class="nav-link {% if 'categories' in request.endpoint %}active{% endif %}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Categorias</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Listas</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Alertas de estoque baixo</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Opções</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item menu-closed">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-shopping-cart"></i>
              <p>
                Logística
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Pedidos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Estatísticas</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Parceiros</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item menu-closed">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Clientes
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Clientes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Requisições de Alerta de Estoque</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item menu-closed">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-bullhorn"></i>
              <p>
                Ofertas
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Ofertas</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Cupons de desconto</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Séries de cupons</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item menu-closed">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-folder"></i>
              <p>
                Conteúdo
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Páginas</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Templates de e-mail</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link disabled">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Avaliações</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-bar"></i>
              <p>
                Relatórios
              </p>
            </a>
          </li>
        </ul>
      </nav>
      {% endif %}
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>